import type { ModLoader } from '../types/contracts';

export type MappingScope = {
  sourceLoader?: Exclude<ModLoader, 'unknown'>;
  targetLoader?: Exclude<ModLoader, 'unknown'>;
  sourceVersionRange?: string;
  targetVersionRange?: string;
};

export type ImportRenameMapping = MappingScope & {
  id: string;
  from: string;
  to: string;
};

export type ClassRenameMapping = MappingScope & {
  id: string;
  from: string;
  to: string;
};

export type MethodRenameMapping = MappingScope & {
  id: string;
  className?: string;
  from: string;
  to: string;
};

// Generated by scripts/refresh-transform-dataset.mjs. Do not edit manually.
export const IMPORT_RENAME_MAPPINGS: ImportRenameMapping[] = [
  {
    "id": "forge-creative-tab-import",
    "from": "net.minecraft.world.item.CreativeModeTab",
    "to": "net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents",
    "sourceLoader": "forge",
    "targetLoader": "fabric",
    "targetVersionRange": ">=1.19.0"
  },
  {
    "id": "builtin-registries-import-1-20-5",
    "from": "net.minecraft.core.registries.BuiltinRegistries",
    "to": "net.minecraft.core.registries.BuiltInRegistries",
    "targetVersionRange": ">=1.20.5 <1.21.0"
  }
];

export const CLASS_RENAME_MAPPINGS: ClassRenameMapping[] = [
  {
    "id": "builtin-registries-class-1-20-5",
    "from": "BuiltinRegistries",
    "to": "BuiltInRegistries",
    "targetVersionRange": ">=1.20.5 <1.21.0"
  }
];

export const METHOD_RENAME_MAPPINGS: MethodRenameMapping[] = [
  {
    "id": "resource-location-ctor-1-21",
    "className": "ResourceLocation",
    "from": "new ResourceLocation",
    "to": "ResourceLocation.fromNamespaceAndPath",
    "targetVersionRange": ">=1.21.0"
  },
  {
    "id": "creative-tab-prefix-forge-to-fabric",
    "className": "CreativeModeTab",
    "from": "CreativeModeTab",
    "to": "ItemGroupEvents",
    "sourceLoader": "forge",
    "targetLoader": "fabric",
    "targetVersionRange": ">=1.19.0"
  }
];

